baseURL = "https://quangthin1615.github.io/QuangThienWorkshop-template/"
languageCode = "vi-VN"
title = "Báo cáo thực tập AWS"

theme = "hugo-theme-learn"

# =========================
# NGÔN NGỮ
# =========================

defaultContentLanguage = "vi"
defaultContentLanguageInSubdir = true

# =========================
# OUTPUT
# =========================

[outputs]
home = ["HTML", "RSS", "JSON"]

# =========================
# PARAMS
# =========================

[params]
themeVariant = "workshop"
editURL = ""
description = "Báo cáo thực tập AWS"
author = "Phạm Quang Thiện"

showVisitedLinks = true
disableBreadcrumb = false
disableNextPrev = false

# =========================
# TIẾNG VIỆT
# =========================

[languages.vi]
title = "Báo cáo thực tập AWS"
languageName = "Tiếng Việt"
weight = 1
contentDir = "content/vi"

# =========================
# TIẾNG ANH
# =========================

[languages.en]
title = "AWS Internship Report"
languageName = "English"
weight = 2
contentDir = "content/en"

# =========================
# MENU TIẾNG VIỆT
# =========================

[[languages.vi.menu.shortcuts]]
name = "<i class='fab fa-aws'></i> AWS Blog"
identifier = "aws-blog-vi"
url = "https://aws.amazon.com/blogs/"
weight = 20

[[languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "aws-facebook-vi"
url = "https://www.facebook.com/groups/awsstudygroupfcj"
weight = 21

# =========================
# MENU TIẾNG ANH
# =========================

[[languages.en.menu.shortcuts]]
name = "<i class='fab fa-aws'></i> AWS Blog"
identifier = "aws-blog-en"
url = "https://aws.amazon.com/blogs/"
weight = 20

[[languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "aws-facebook-en"
url = "https://www.facebook.com/groups/awsstudygroupfcj"
weight = 21

# =========================
# CACHE
# =========================

[caches]

[caches.images]
dir = ":cacheDir/images"
publishDir = "docs"
